services:
  - type: web
    name: tech-study-finder
    env: python
    region: berlin
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
